# Generated by Django 6.0.5 on 2026-09-01 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LmEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Lettermint message id.', max_length=64, unique=True)),
                ('from_email', models.CharField(max_length=254)),
                ('to', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('subject', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('suppressed', 'Suppressed'), ('processed', 'Processed'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('soft_bounced', 'Soft bounced'), ('hard_bounced', 'Hard bounced'), ('spam_complaint', 'Spam complaint'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('policy_rejected', 'Policy rejected'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=32)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lettermint email message',
                'verbose_name_plural': 'Lettermint email messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='lm_message_status_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='LmEmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Lettermint webhook event id, used for de-duplication.', max_length=64, unique=True)),
                ('message_id', models.CharField(db_index=True, help_text='Lettermint message id.', max_length=64)),
                ('event', models.CharField(db_index=True, help_text='Webhook event type, e.g. "message.hard_bounced".', max_length=64)),
                ('recipient', models.CharField(blank=True, db_index=True, max_length=254)),
                ('reason', models.TextField(blank=True, help_text='Human-readable failure or bounce reason.')),
                ('reason_code', models.CharField(blank=True, help_text='Machine-readable reason code or enhanced SMTP status code.', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict, help_text="Raw 'data' object of the webhook payload.")),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(blank=True, help_text='Empty when the message was not sent through this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='lettermint_django.lmemailmessage')),
            ],
            options={
                'verbose_name': 'Lettermint email event',
                'verbose_name_plural': 'Lettermint email events',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
