# Generated by Django 6.0.5 on 2026-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettermint_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmemailmessage',
            name='tag',
            field=models.CharField(blank=True, db_index=True, help_text='Lettermint tag, e.g. a campaign name.', max_length=100),
        ),
    ]
