# Generated by Django 6.0.5 on 2026-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettermint_django', '0002_lmemailmessage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmemailmessage',
            name='bulk_id',
            field=models.CharField(blank=True, db_index=True, help_text='Id of the send_bulk call this message was part of; empty for single sends.', max_length=64),
        ),
    ]
