# Generated by Django 6.0.5 on 2026-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettermint_django', '0003_lmemailmessage_bulk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmemailmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('queued', 'Queued'), ('suppressed', 'Suppressed'), ('processed', 'Processed'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('soft_bounced', 'Soft bounced'), ('hard_bounced', 'Hard bounced'), ('spam_complaint', 'Spam complaint'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('policy_rejected', 'Policy rejected'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=32),
        ),
    ]
